/* Generated By:JJTree&JavaCC: Do not edit this line. HLConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADD = 5;
  /** RegularExpression Id. */
  int AND = 6;
  /** RegularExpression Id. */
  int ASSIGN = 7;
  /** RegularExpression Id. */
  int COL = 8;
  /** RegularExpression Id. */
  int COMMA = 9;
  /** RegularExpression Id. */
  int DIV = 10;
  /** RegularExpression Id. */
  int DOT = 11;
  /** RegularExpression Id. */
  int EQ = 12;
  /** RegularExpression Id. */
  int GE = 13;
  /** RegularExpression Id. */
  int GT = 14;
  /** RegularExpression Id. */
  int LE = 15;
  /** RegularExpression Id. */
  int LT = 16;
  /** RegularExpression Id. */
  int LSQUARE = 17;
  /** RegularExpression Id. */
  int LPAREN = 18;
  /** RegularExpression Id. */
  int MOD = 19;
  /** RegularExpression Id. */
  int NE = 20;
  /** RegularExpression Id. */
  int NOT = 21;
  /** RegularExpression Id. */
  int OR = 22;
  /** RegularExpression Id. */
  int PROD = 23;
  /** RegularExpression Id. */
  int RSQUARE = 24;
  /** RegularExpression Id. */
  int RPAREN = 25;
  /** RegularExpression Id. */
  int SEMICOL = 26;
  /** RegularExpression Id. */
  int SUB = 27;
  /** RegularExpression Id. */
  int DO = 28;
  /** RegularExpression Id. */
  int ELIF = 29;
  /** RegularExpression Id. */
  int ELSE = 30;
  /** RegularExpression Id. */
  int FI = 31;
  /** RegularExpression Id. */
  int FOR = 32;
  /** RegularExpression Id. */
  int FUN = 33;
  /** RegularExpression Id. */
  int IF = 34;
  /** RegularExpression Id. */
  int IN = 35;
  /** RegularExpression Id. */
  int INT = 36;
  /** RegularExpression Id. */
  int LIST = 37;
  /** RegularExpression Id. */
  int NUF = 38;
  /** RegularExpression Id. */
  int OD = 39;
  /** RegularExpression Id. */
  int PRINT = 40;
  /** RegularExpression Id. */
  int RETURN = 41;
  /** RegularExpression Id. */
  int STR = 42;
  /** RegularExpression Id. */
  int THEN = 43;
  /** RegularExpression Id. */
  int WHILE = 44;
  /** RegularExpression Id. */
  int DIGIT = 45;
  /** RegularExpression Id. */
  int LETTER = 46;
  /** RegularExpression Id. */
  int INTEGER = 47;
  /** RegularExpression Id. */
  int IDENTIFIER = 48;
  /** RegularExpression Id. */
  int STRING = 54;
  /** RegularExpression Id. */
  int COMMENT_SINGlE = 61;
  /** RegularExpression Id. */
  int COMMENT_MULTI = 63;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int INSTRING = 1;
  /** Lexical state. */
  int INCOMMENT0 = 2;
  /** Lexical state. */
  int INCOMMENT1 = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"+\"",
    "\"&\"",
    "\"=\"",
    "\":\"",
    "\",\"",
    "\"/\"",
    "\".\"",
    "\"==\"",
    "\">=\"",
    "\">\"",
    "\"<=\"",
    "\"<\"",
    "\"[\"",
    "\"(\"",
    "\"%\"",
    "\"!=\"",
    "\"!\"",
    "\"|\"",
    "\"*\"",
    "\"]\"",
    "\")\"",
    "\";\"",
    "\"-\"",
    "\"DO\"",
    "\"ELIF\"",
    "\"ELSE\"",
    "\"FI\"",
    "\"FOR\"",
    "\"FUN\"",
    "\"IF\"",
    "\"IN\"",
    "\"INT\"",
    "\"LIST\"",
    "\"NUF\"",
    "\"OD\"",
    "\"PRINT\"",
    "\"RETURN\"",
    "\"STR\"",
    "\"THEN\"",
    "\"WHILE\"",
    "<DIGIT>",
    "<LETTER>",
    "<INTEGER>",
    "<IDENTIFIER>",
    "\"\\\"\"",
    "\"\\\\\\\\\"",
    "\"\\\\\\\"\"",
    "\"\\\\t\"",
    "\"\\\\n\"",
    "\"\\\"\"",
    "<token of kind 55>",
    "<token of kind 56>",
    "<token of kind 57>",
    "<token of kind 58>",
    "<token of kind 59>",
    "<token of kind 60>",
    "<COMMENT_SINGlE>",
    "\"/*\"",
    "\"*/\"",
    "\"/*\"",
    "<token of kind 65>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 68>",
    "\"while\"",
  };

}
